name: Post deployment metadata to app insights

on:
  push:
    branches: [ check ]
    paths: [ .github/workflows/post-metadata.yml ]

jobs:
  post-logs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        name: Checkout action code
        with:
          ref: dev
          path: action
          
      - name: Post deployment metadata
        uses: ./action
        with:
          target: la
          log-type: 'deploymentMetadata'
          connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
          workspace-id: ${{ secrets.AZ_LA_WORKSPACE_ID }}
          workspace-secret: ${{ secrets.AZ_LA_WORKSPACE_SECRET }}
          deployment-metadata-path: '.github/data/deployment-metadata.json'